import numpy as np
import ufl

from mpi4py import MPI
from petsc4py import PETSc
from dolfinx import fem
from dolfinx.fem.petsc import LinearProblem

from parameters import (
    CELL_TAGS,
    h_afl,
    sigma_anode,
    sigma_blocked,
    phi_e_collector,
    phi_e_bc_z,
)
from material_degradation import metal_support_conductivity
from submesh_utils_level2 import dg0_from_cell_values, cell_mean_cg1

"""
Electronic potential PDE for the fuel-side solid/electrode network.

Solves a conservative electronic-conduction equation:
    -div(sigma_e grad(phi_e)) = q_e
"""

def cell_tags_as_array(mesh, cell_tags):
    """
    Return one cell tag per owned cell.
    """
    n_local     = mesh.topology.index_map(mesh.topology.dim).size_local
    tag_by_cell = np.full(n_local, -1, dtype=np.int32)
    for cell, tag in zip(cell_tags.indices, cell_tags.values):
        if int(cell) < n_local:
            tag_by_cell[int(cell)] = int(tag)
    return tag_by_cell


def dg0_cell_values(function):
    """
    Return one scalar DG0 value per owned cell.
    """
    V          = function.function_space
    mesh       = V.mesh
    n_local    = mesh.topology.index_map(mesh.topology.dim).size_local
    out = np.zeros(n_local, dtype=float)
    for c in range(n_local):
        dofs   = V.dofmap.cell_dofs(c)
        out[c] = float(function.x.array[dofs[0]])
    return out


def make_electronic_conductivity_field(mesh, cell_tags, theta_metal):
    """
    Build DG0 electronic conductivity field sigma_e [S/m] on the fuel submesh.

    Conducting domains in this reduced fuel-side PDE:
      - metal support: oxidation-dependent sigma_metal(theta)
      - anode functional layer: fixed sigma_anode

    Non-electronic/gas regions are assigned sigma_blocked.
    """
    n_local              = mesh.topology.index_map(mesh.topology.dim).size_local
    tags                 = cell_tags_as_array(mesh, cell_tags)
    theta_cell           = np.clip(cell_mean_cg1(theta_metal), 0.0, 1.0)

    sigma                = np.full(n_local, sigma_blocked, dtype=float)

    metal_support        = tags == CELL_TAGS["metal_support"]
    afl                  = tags == CELL_TAGS["anode_functional_layer"]

    sigma[metal_support] = metal_support_conductivity(theta_cell[metal_support])
    sigma[afl]           = sigma_anode

    return dg0_from_cell_values(mesh, sigma, "sigma_electron")


def make_electron_source_field(mesh, fuel_afl_cells, i_local_fuel):
    """
    Convert shared local current density to a volumetric electronic source q_e.

    i_local_fuel is [A/m2] assigned in AFL cells.  The electron-conduction PDE
    needs [A/m3], so the source is i/h_afl inside the AFL.

    q_e > 0 means electrons are generated by the anode reaction.
    """
    n_local           = mesh.topology.index_map(mesh.topology.dim).size_local
    i_cell            = dg0_cell_values(i_local_fuel)
    q                 = np.zeros(n_local, dtype=float)
    q[fuel_afl_cells] = i_cell[fuel_afl_cells] / h_afl
    return dg0_from_cell_values(mesh, q, "q_electron_source")


def locate_phi_e_collector_bc(V):
    """
    Apply electronic-potential reference/current-collector boundary condition.

    In this reduced fuel submesh, the fuel ribs/current collector are not part of
    the gas submesh.  We therefore approximate the collector as the plane
    z = phi_e_bc_z, usually z_fuel_top: the bottom side of the metal support.
    """
    mesh     = V.mesh
    tol      = 1.0e-10

    def marker(x):
        return np.isclose(x[2], float(phi_e_bc_z), atol=tol)

    dofs     = fem.locate_dofs_geometrical(V, marker)
    n_global = mesh.comm.allreduce(len(dofs), op=MPI.SUM)
    if n_global == 0:
        raise RuntimeError(
            "No DOFs found for electron-potential collector BC. "
            "Check phi_e_bc_z in parameters.py."
        )

    return fem.dirichletbc(PETSc.ScalarType(phi_e_collector), dofs, V)


def solve_electron_potential(mesh, V_phi, sigma_electron, q_electron):
    """
    Solve -div(sigma_e grad(phi_e)) = q_e on the fuel submesh.

    Weak form:
        int sigma_e grad(phi_e).grad(v) dx = int q_e v dx
    """
    phi         = ufl.TrialFunction(V_phi)
    v           = ufl.TestFunction(V_phi)
    dx          = ufl.dx(domain=mesh)

    bc          = locate_phi_e_collector_bc(V_phi)

    a           = sigma_electron * ufl.dot(ufl.grad(phi), ufl.grad(v)) * dx
    L           = q_electron * v * dx

    problem     = LinearProblem(a, L,
                                bcs=[bc],
                                petsc_options_prefix = "phi_electron_",
                                petsc_options={"ksp_type": "cg",
                                           "pc_type": "hypre",
                                           "ksp_rtol": 1.0e-8,
                                           "ksp_atol": 1.0e-10,
                                           },
                                           )
    phi_e       = problem.solve()
    phi_e.name  = "phi_electron"
    phi_e.x.scatter_forward()
    return phi_e


def project_electron_current_density(mesh, V_vec, phi_e, sigma_electron):
    """
    Project electronic current density j_e = -sigma_e grad(phi_e) [A/m2].
    """
    j       = ufl.TrialFunction(V_vec)
    w       = ufl.TestFunction(V_vec)
    dx      = ufl.dx(domain=mesh)

    expr    = -sigma_electron * ufl.grad(phi_e)

    problem = LinearProblem(ufl.inner(j, w) * dx,
                            ufl.inner(expr, w) * dx,
                            petsc_options_prefix = "j_electron_projection_",
                            petsc_options = {"ksp_type": "cg", 
                                             "pc_type" : "jacobi", 
                                             "ksp_rtol": 1.0e-8},
                                             )
    j_e     = problem.solve()
    j_e.name= "j_electron"
    j_e.x.scatter_forward()
    
    return j_e


def project_electron_current_magnitude(mesh, V_scalar, phi_e, sigma_electron):
    """
    Project |j_e| = |sigma_e grad(phi_e)| [A/m2] to a scalar field.
    """
    j_mag   = ufl.TrialFunction(V_scalar)
    v       = ufl.TestFunction(V_scalar)
    dx      = ufl.dx(domain=mesh)

    j_vec   = -sigma_electron * ufl.grad(phi_e)
    expr    = ufl.sqrt(ufl.dot(j_vec, j_vec) + 1.0e-30)

    problem = LinearProblem(j_mag * v * dx,
                            expr * v * dx,
                            petsc_options_prefix = "j_electron_mag_projection_",
                            petsc_options = {"ksp_type" : "cg",
                                              "pc_type" : "jacobi", 
                                              "ksp_rtol": 1.0e-8},
                                              )
    out     = problem.solve()
    out.name= "j_electron_mag"
    out.x.scatter_forward()
    
    return out
